# Parte 2

# Clasificacion

In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.svm import SVC # Supprt Vector Classifier
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc

from sklearn.exceptions import UndefinedMetricWarning

In [2]:
data = pd.read_csv('wine_fraud_cleanedv2.csv')

In [ ]:
data

Unnamed: 0  fixed acidity  volatile acidity  citric acid  \
0              0            7.4              0.70         0.00   
1              2            7.8              0.76         0.04   
2              4            7.4              0.70         0.00   
3              5            7.4              0.66         0.00   
4              6            7.9              0.60         0.06   
...          ...            ...               ...          ...   
6004        6492            6.2              0.21         0.29   
6005        6493            6.6              0.32         0.36   
6006        6494            6.5              0.24         0.19   
6007        6495            5.5              0.29         0.30   
6008        6496            6.0              0.21         0.38   

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0                1.9      0.076                 11.0                  34.0   
1                2.3      0.092                 15.0                  54.0   
2                1.9      0.076                 11.0                  34.0   
3                1.8      0.075                 13.0                  40.0   
4                1.6      0.069                 15.0                  59.0   
...              ...        ...                  ...                   ...   
6004             1.6      0.039                 24.0                  92.0   
6005             8.0      0.047                 57.0                 168.0   
6006             1.2      0.041                 30.0                 111.0   
6007             1.1      0.022                 20.0                 110.0   
6008             0.8      0.020                 22.0                  98.0   

      density    pH  sulphates  alcohol  quality  type  
0     0.99780  3.51       0.56      9.4        1     0  
1     0.99700  3.26       0.65      9.8        1     0  
2     0.99780  3.51       0.56      9.4        1     0  
3     0.99780  3.51       0.56      9.4        1     0  
4     0.99640  3.30       0.46      9.4        1     0  
...       ...   ...        ...      ...      ...   ...  
6004  0.99114  3.27       0.50     11.2        1     1  
6005  0.99490  3.15       0.46      9.6        1     1  
6006  0.99254  2.99       0.46      9.4        1     1  
6007  0.98869  3.34       0.38     12.8        1     1  
6008  0.98941  3.26       0.32     11.8        1     1  

[6009 rows x 14 columns]

# **SVM LINEAL**

In [3]:
X = data[[ 'volatile acidity', 'citric acid', 'chlorides',  'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]
y = data['quality']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
svm_model = SVC(kernel='linear', class_weight='balanced')
svm_model.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='linear')

In [6]:
y_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

In [7]:
tn, fp, fn, tp = confusion.ravel()
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)

In [8]:
f1_score = classification_report(y_test, y_pred)

In [9]:
fpr, tpr, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(fpr, tpr)

In [10]:
scores = cross_val_score(svm_model, X, y, cv=5)

In [11]:
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Sensitivity:", sensitivity)
print("Specificity:", specificity)
print("F1 Score:\n", f1_score)
print("AUC:", roc_auc)
print("Cross Validation Scores:", scores)
print("Mean CV Score:", np.mean(scores))

Accuracy: 0.6863560732113144
Confusion Matrix:
 [[ 19  12]
 [365 806]]
Sensitivity: 0.6883005977796754
Specificity: 0.6129032258064516
F1 Score:
               precision    recall  f1-score   support

           0       0.05      0.61      0.09        31
           1       0.99      0.69      0.81      1171

    accuracy                           0.69      1202
   macro avg       0.52      0.65      0.45      1202
weighted avg       0.96      0.69      0.79      1202

AUC: 0.6506019117930635
Cross Validation Scores: [0.06489185 0.65640599 0.76455907 0.83777038 0.80099917]
Mean CV Score: 0.6249252910428221


# **SVM RBF**

In [12]:
X = data[[ 'volatile acidity', 'citric acid', 'chlorides',  'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]
y = data['quality']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
svm_model = SVC(kernel='rbf', class_weight='balanced')
svm_model.fit(X_train, y_train)

SVC(class_weight='balanced')

In [15]:
y_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

In [16]:
tn, fp, fn, tp = confusion.ravel()
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)

In [17]:
f1_score = classification_report(y_test, y_pred)

In [18]:
fpr, tpr, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(fpr, tpr)

In [19]:
scores = cross_val_score(svm_model, X, y, cv=5)

In [ ]:
print("Parametros de rendimiento para SVM RBF\n")
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Sensitivity:", sensitivity)
print("Specificity:", specificity)
print("F1 Score:\n", f1_score)
print("AUC:", roc_auc)
print("Cross Validation Scores:", scores)
print("Mean CV Score:", np.mean(scores))

Parametros de rendimiento para SVM RBF

Accuracy: 0.6447587354409318
Confusion Matrix:
 [[ 14  17]
 [410 761]]
Sensitivity: 0.6498719043552519
Specificity: 0.45161290322580644
F1 Score:
               precision    recall  f1-score   support

           0       0.03      0.45      0.06        31
           1       0.98      0.65      0.78      1171

    accuracy                           0.64      1202
   macro avg       0.51      0.55      0.42      1202
weighted avg       0.95      0.64      0.76      1202

AUC: 0.5507424037905292
Cross Validation Scores: [0.11148087 0.64725458 0.70798669 0.74542429 0.7785179 ]
Mean CV Score: 0.598132864875499


# **SVM SIGMOID**

In [20]:
X = data[[ 'volatile acidity', 'citric acid', 'chlorides',  'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]
y = data['quality']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
svm_model = SVC(kernel='sigmoid', class_weight='balanced')
svm_model.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='sigmoid')

In [23]:
y_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

In [24]:
tn, fp, fn, tp = confusion.ravel()
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)

In [25]:
f1_score = classification_report(y_test, y_pred)

In [26]:
fpr, tpr, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(fpr, tpr)

In [27]:
scores = cross_val_score(svm_model, X, y, cv=5)

In [ ]:
print("Parametros de rendimiento para SVM RBF\n")
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Sensitivity:", sensitivity)
print("Specificity:", specificity)
print("F1 Score:\n", f1_score)
print("AUC:", roc_auc)
print("Cross Validation Scores:", scores)
print("Mean CV Score:", np.mean(scores))

Parametros de rendimiento para SVM RBF

Accuracy: 0.5341098169717138
Confusion Matrix:
 [[ 15  16]
 [544 627]]
Sensitivity: 0.5354397950469684
Specificity: 0.4838709677419355
F1 Score:
               precision    recall  f1-score   support

           0       0.03      0.48      0.05        31
           1       0.98      0.54      0.69      1171

    accuracy                           0.53      1202
   macro avg       0.50      0.51      0.37      1202
weighted avg       0.95      0.53      0.67      1202

AUC: 0.509655381394452
Cross Validation Scores: [0.25291181 0.36522463 0.37271215 0.5249584  0.5928393 ]
Mean CV Score: 0.4217292577871186


# **SVM POLINOMICO**

In [28]:
X = data[[ 'volatile acidity', 'citric acid', 'chlorides',  'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]
y = data['quality']

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
svm_model = SVC(kernel='poly', class_weight='balanced')
svm_model.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='poly')

In [31]:
y_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

In [32]:
tn, fp, fn, tp = confusion.ravel()
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)

In [33]:
f1_score = classification_report(y_test, y_pred)

In [34]:
fpr, tpr, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(fpr, tpr)

In [35]:
scores = cross_val_score(svm_model, X, y, cv=5)

In [ ]:
print("Parametros de rendimiento para SVM RBF\n")
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Sensitivity:", sensitivity)
print("Specificity:", specificity)
print("F1 Score:\n", f1_score)
print("AUC:", roc_auc)
print("Cross Validation Scores:", scores)
print("Mean CV Score:", np.mean(scores))

Parametros de rendimiento para SVM RBF

Accuracy: 0.6098169717138103
Confusion Matrix:
 [[ 15  16]
 [453 718]]
Sensitivity: 0.6131511528608027
Specificity: 0.4838709677419355
F1 Score:
               precision    recall  f1-score   support

           0       0.03      0.48      0.06        31
           1       0.98      0.61      0.75      1171

    accuracy                           0.61      1202
   macro avg       0.51      0.55      0.41      1202
weighted avg       0.95      0.61      0.74      1202

AUC: 0.5485110603013691
Cross Validation Scores: [0.05990017 0.7063228  0.7953411  0.75374376 0.74854288]
Mean CV Score: 0.6127701402464114


# GRID SEARCH

In [36]:
grid = {'C':[0.001, 0.01, 0.1, 0.5, 1],
             'kernel':['linear', 'rbf', 'poly', 'sigmoid'],
              'gamma':['scale', 'auto'],
              'degree':[2, 3, 4],
              'class_weight':['balanced']}

svm = SVC()
gs = GridSearchCV(svm, param_grid = grid)

gs.fit(X_train, y_train)
gs.best_params_

{'C': 0.001,
 'class_weight': 'balanced',
 'degree': 4,
 'gamma': 'auto',
 'kernel': 'poly'}

# CONCLUSIÓN

Como se puede ver en la exactitud de los modelos SVM, el que tuvo la mejor exactitud es del SVM RBF, además que un plus que tiene es el nivel de sensibilidad del modelo; ya que si tratamos con datos reales, este puede mostrarnos una mejor vista de los resultados.